// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfxMaAE_NwYHB_oztCh_TvPrgDEoBAYKA',
    appId: '1:25487299842:web:24d36298ab8d5b262b9e1b',
    messagingSenderId: '25487299842',
    projectId: 'vize-30120070',
    authDomain: 'vize-30120070.firebaseapp.com',
    storageBucket: 'vize-30120070.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUAjR1cAFM63Ji7irHPzeZIaCSO350V3Y',
    appId: '1:25487299842:android:beed909fa60784942b9e1b',
    messagingSenderId: '25487299842',
    projectId: 'vize-30120070',
    storageBucket: 'vize-30120070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0RkswsnGlz16P242BltRgGkNLq8xpjtw',
    appId: '1:25487299842:ios:f10ef62c10cf888d2b9e1b',
    messagingSenderId: '25487299842',
    projectId: 'vize-30120070',
    storageBucket: 'vize-30120070.appspot.com',
    iosClientId: '25487299842-5it0h8isg34dv0rtdh462jb66gd2siif.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0RkswsnGlz16P242BltRgGkNLq8xpjtw',
    appId: '1:25487299842:ios:f10ef62c10cf888d2b9e1b',
    messagingSenderId: '25487299842',
    projectId: 'vize-30120070',
    storageBucket: 'vize-30120070.appspot.com',
    iosClientId: '25487299842-5it0h8isg34dv0rtdh462jb66gd2siif.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
